### ISSUE TITLE
Question: How to merge 2 VB assemblies that have embedded VB runtime?

### ISSUE THREAD

**Issue by Nukepayload2** [tom-englert/ILMerge.Fody#14]
## Steps
- Create 2 VB class libraries named `ProjectA` and `ProjectB`.
- Edit project files. In property group, set `<VBRuntime>Embed</VBRuntime>`.
- In `ProjectA`, add project reference to ProjectB.
- Use `ILMerge.Fody` to merge these assemblies.

## Actual behavior
IL Import failed: Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute already exists in target module.

## Expected behavior
Deduplicate embedded VB runtime instead of throwing exception.

## Note
1. We don't want to use `NamespacePrefix`. Because it breaks some code of `ProjectB` that uses reflections.
2. `StandardModuleAttribute` has a custom attribute named `Microsoft.VisualBasic.Embedded`. It can be used to mark types of embedded VB runtime.

**Comment by tom-englert** [comment]
Why not let ILMerge embedd the runtime?

**Comment by Nukepayload2** [comment]
@tom-englert I'm writing a plugin (`ProjectA`) for a self-contained mono program. The mono runtime was trimmed. It throws `TypeLoadException` if I use the VB runtime of .NET Framework or the VB runtime on NuGet.org. So, I have to use the embedded VB runtime. My `ProjectA` references to many helper packages. One of them is `ProjectB`, which also has embedded VB runtime. So, when publishing `ProjectA`, its embedded VB runtime conflicts with `ProjectB`.

**Comment by tom-englert** [comment]
If you're a patron of Fody you can provide a PR, or you can build your own custom merger

**Comment by Nukepayload2** [comment]
@tom-englert 
Ok, I'll try to build my custom merger. I'm unable to use Patron because of region lock.

I'll fork this tool and edit `CodeImporter.IsEmbeddedType` to fix this bug.
https://github.com/tom-englert/FodyTools/blob/958065e93ceba0ecfb59b8bf568532f0d467f9be/FodyTools/CodeImporter.cs#L1268
