### ISSUE TITLE
Is there a way to change the namespace of merged assemblies?

### ISSUE THREAD

**Issue by JobaDiniz** [tom-englert/ILMerge.Fody#2]
I'm merging assemblies and making them [public](https://github.com/tom-englert/ILMerge.Fody/issues/1), however I'd like to change their namespaces, is that possible?

**Comment by tom-englert** [comment]
https://github.com/tom-englert/FodyTools/blob/42fb0fd8cd37f4194b68865cbdca4c17d2eb5d5a/FodyTools/CodeImporter.cs#L72

**Comment by JobaDiniz** [comment]
Sorry, but I'm pretty new to the Fody project, how can I set that function?

**Comment by tom-englert** [comment]
Sorry, wrong context - no, the ILMerge - weaver does not support this.

**Comment by tom-englert** [comment]
@JobaDiniz V1.11 now supports a namespace prefix: https://github.com/tom-englert/ILMerge.Fody#namespaceprefix
