### ISSUE TITLE
No support for duplicated types?

### ISSUE THREAD

**Issue by ajaskiewiczpl** [tom-englert/ILMerge.Fody#8]
ILMerge supports the `/allowDup` command line argument to allow duplicated types. However when I try to use ILMerge.Fody, in runtime I get the error `System.BadImageFormatException Duplicate type with name 'System.Web.Http.Error' in assembly [...]`. Is there a reason why it's not supported?

**Comment by tom-englert** [comment]
I did not see a use case for this. When would you have two assemblies having e.g. `System.Web.Http` already embedded?

**Comment by tom-englert** [comment]
No feedback, closed as stale

**Comment by otuncelli** [comment]
I'd like to suggest reopening this issue.

Introduced with C# 7.2, readonly structs are causing `System.Runtime.CompilerServices.IsReadOnlyAttribute` and `Microsoft.CodeAnalysis.EmbeddedAttribute` types to be embedded in the resulting assembly. And they cause this issue if multiple assemblies are containing it.

Note: In my tests `netstandard2.1` and beyond are not affected by this issue.

```csharp
class Program
{
	static void Main(string[] args)
	{
		Console.WriteLine("Hello World!");
	}

	public readonly struct Test
	{
	}
}
```

Thanks.

**Comment by tom-englert** [comment]
@otuncelli that should be already working. 
Anything with the `[Embedded]` attribute is replaced with the existing target type.
I'm using this heavily for assemblies with nullable reference types.
Can you provide a sample where this is not working?

**Comment by otuncelli** [comment]
I'm currently working with [PdfPig](https://github.com/UglyToad/PdfPig) Library. It contains these readonly structs in its different assemblies. 

The error message I get when I try debugging:
![image](https://user-images.githubusercontent.com/5532796/131338665-9638c889-3ed7-4800-bd9d-af8f36bbd605.png)

ILSpy of resulting assembly:
![image](https://user-images.githubusercontent.com/5532796/131338089-8ea8782b-0f0d-47b7-b177-b4f7d7a7e923.png)

My Configuration:
```xml
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
	<ILMerge NamespacePrefix="PdfFileTypePlugin">
		<IncludeAssemblies>PDFiumSharp|UglyToad.PdfPig.Core|UglyToad.PdfPig|UglyToad.PdfPig.DocumentLayoutAnalysis|UglyToad.PdfPig.Fonts|UglyToad.PdfPig.Package|UglyToad.PdfPig.Tokenization|UglyToad.PdfPig.Tokens</IncludeAssemblies>
		<FullImport>true</FullImport>
	</ILMerge>
</Weavers>
```

**Comment by tom-englert** [comment]
@otuncelli can you try V 1.18?

**Comment by otuncelli** [comment]
Solved! Thank you very much.

**Comment by tom-englert** [comment]
> It seems to happen only when I use NamespacePrefix

That was the key information
